MENU_PRINCIPAL = "MENU_PRINCIPAL"

# Flujo consulta disponibilidad
CONSULTA_FECHA_CHECKIN = "CONSULTA_FECHA_CHECKIN"
CONSULTA_FECHA_CHECKOUT = "CONSULTA_FECHA_CHECKOUT"
CONSULTA_PERSONAS = "CONSULTA_PERSONAS"
MOSTRANDO_DISPONIBILIDAD = "MOSTRANDO_DISPONIBILIDAD"

# Flujo reserva
SELECCION_CABANA = "SELECCION_CABANA"
CAPTURA_NOMBRE = "CAPTURA_NOMBRE"
CAPTURA_DNI = "CAPTURA_DNI"
CAPTURA_TELEFONO = "CAPTURA_TELEFONO"
SELECCION_MODALIDAD_PAGO = "SELECCION_MODALIDAD_PAGO"
CONFIRMACION_RESERVA = "CONFIRMACION_RESERVA"
ESPERA_COMPROBANTE = "ESPERA_COMPROBANTE"
COMPROBANTE_RECIBIDO = "COMPROBANTE_RECIBIDO"

# Flujo modificacion
MODIFICACION_PEDIR_CODIGO = "MODIFICACION_PEDIR_CODIGO"
MODIFICACION_NUEVA_CHECKIN = "MODIFICACION_NUEVA_CHECKIN"
MODIFICACION_NUEVA_CHECKOUT = "MODIFICACION_NUEVA_CHECKOUT"
MODIFICACION_CONFIRMACION = "MODIFICACION_CONFIRMACION"

# Flujo cancelacion
CANCELACION_PEDIR_CODIGO = "CANCELACION_PEDIR_CODIGO"
CANCELACION_CONFIRMACION = "CANCELACION_CONFIRMACION"

# Palabras clave globales que siempre vuelven al menu
PALABRAS_MENU = {"menu", "inicio", "hola", "cancelar", "salir"}
